### ISSUE TITLE
Updating for v5

### ISSUE THREAD

**Issue by sophodev** [fastify/fastify-rate-limit#333]
Hi 👋🏾 I'm Eliphaz **Bouye**, and would like to work on this.

**Comment by jsumners** [comment]
I think it would be a good idea to coordinate with @gurgunday on this one. He has been doing a lot of work in this repo, and a new major should be released soon. After that, prepping a `next` branch should be easy to do.

**Comment by gurgunday** [comment]
I’m down!

**Comment by Eliphaz-Bouye** [comment]
Ok, nice :)
So @gurgunday  what's the starting point?

**Comment by gurgunday** [comment]
Yeah so the first todo is to determine if the package should be archived -- the answer to which is a short no because we all love rate limiting ;)

Now that we crossed that off, let's move on to the second:

- We need to update the [CI workflow](https://github.com/fastify/fastify-rate-limit/blob/3b9420750d03deaafc049a2f30f4720f97737035/.github/workflows/ci.yml#L62C39-L62C39) so that it only uses node versions 18, 20, and 21
- We need to update the dependencies -- you can simply do a `npx npm-check-updates -u` to upgrade all the dependencies to their latest versions, if major updates are available and upgrading breaks tests, we need to deal with them
- There is potentially something else to do but I will need to ask around first

I will also create the `next` branch so that you can target it with PRs

**Comment by Eliphaz-Bouye** [comment]
Great let's go 🚀

**Comment by Eliphaz-Bouye** [comment]
@gurgunday I have a question why `tap` need to be pin to `16.3.9` and not the latest version as other package by running `npx npm-check-updates -u` ?

**Comment by Eliphaz-Bouye** [comment]
@gurgunday  updating is done :) .
 Can you create the `next` branch where I can target them to my PR?

**Comment by jsumners** [comment]
Done https://github.com/fastify/fastify-rate-limit/tree/next

**Comment by gurgunday** [comment]
Every task here has been completed except the workflow update (#350)

Will be tracking that from https://github.com/fastify/fastify-rate-limit/issues/340

Thanks again for the contribution
