### ISSUE TITLE
Rate limiting without a handler

### ISSUE THREAD

**Issue by ddsultan** [fastify/fastify-rate-limit#58]
## 🚀 Feature Proposal

It would be really helpful if one could add route based rate limiting without a `handler` function. 

## Motivation

I am using Fastify as a gateway in combination with [fastify-gateway](https://github.com/jkyberneees/fastify-gateway). With the gateway plugin (`fastify-gateway`) I can delegate handling to external services. By being able to add route based rate limiter without a handler parameter we can make the `fastify-rate-limit` plugin usable beyond typical route based rate limiting.

## Example

**Expected Behaviour:**

```js 
fastify.register(fastifyRateLimit, { //just as an option
  config: {
    route: '/routeX',
    rateLimit: {
      max: 3,
      timeWindow: '1 minute'
    }
  }
})
```

**Comment by mcollina** [comment]
This should already be supported: look at the example in https://github.com/fastify/fastify-rate-limit/blob/master/README.md#usage. M

**Comment by ddsultan** [comment]
@mcollina, Thank you for your response. If I am not mistaken the reference you have provided does not do route based rate limiting but global rate limiting

**Comment by Eomm** [comment]
I don't think this feature should be added here: it has too many side effect.

The problem here is that `fastify-gateway` is registering routes for you, without passing the [necessary config](https://github.com/fastify/fastify-rate-limit#options-on-the-endpoint-itself).

So you should ask for a change here:

https://github.com/jkyberneees/fastify-gateway/blob/3ca4e22f2982245fdeb2efd77792964d3c871f02/index.js#L53

adding a new parameter as input to give to the route creation.

Otherwise, you can do it by yourself using the [`onRoute` hook](https://github.com/fastify/fastify/blob/master/docs/Hooks.md#onroute) and write some code:

```
fastify.addHook('onRoute', (routeOptions) => {
if(routeOptions.url === '/routeX' ){
  routeOptions.config.rateLimit: {
      max: 3,
      timeWindow: '1 minute'
    }
}
...
})
```
(this hook must be registered before the `fastify-rate-limit` plugin).
In this way, it should works
